name: Build and Test
on:
  pull_request:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - doc
      - docs

jobs:
  build-and-test:

    # See https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
    if: (! contains(github.event.head_commit.message, '[skip ci]')                   &&
                  ((github.event_name                             != 'pull_request') ||
                   (github.event.pull_request.head.repo.full_name !=
                    github.event.pull_request.base.repo.full_name))
        )

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        py: [311]
        allow-fail: [false]

    steps:
      - uses: actions/checkout@v3.5.3
