name: Build and Test
on:
  pull_request:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - doc
      - docs
jobs:

  build-and-test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        py: [311]
        allow-fail: [false]

    steps:
      - uses: actions/checkout@v3.5.3
